
#TOML settings file thoughts. (in TOML!)

#headings create objects and below them key = value or key = [value,{metadata}]
#doing it bothways allows for a simpler settings file but also allows to give hints on
#conversions or visualization metadata. 
[engine]
project_path=["ClonerSource_dev",{type="string", test="", restart="full"}]
#Seconds before idle happens. 300 = 5 minutes.
idle_timeout=600
#extra settings files that will be added to app_settings or engine as appropriate.
[engine.extra]
app_settings = [
  "content_settings.toml",
  "menu.toml",
]

engine = [
  "bridgesync.toml",
  "engine.font.toml"
]

[engine.reload]
paths = [
  {path = "%APP%/data/", recurse = true},
  {path = "%APP%/settings/", recurse = true},
  {path = "%APP%/qml/", recurse = true},
]
#reload path to data. this is disabled for now.
prefixes = [
  {from = "qrc:/qt/qml/ClonerSource/", to = "file:///%APP%/"},
  {from = "qrc:/qt/qml/Dsqt/", to = "file:///%ENV%(DS_QT_PLATFORM_100)/Library/Dsqt"},
]

[engine.window]
mode = "window"
displayIndex = 0
width = 3840
height = 2160

#need to fix the scaleLoader it is currently broken
[engine.scaleLoader]
world_dimensions=[{w=3840,h=2160},{type="size"}] #The size of the overall app space.
source={x=0,y=0,w=3840,h=2160} #the rectangle of the world space to render.
destination={x=0,y=100,w=3840,h=2160}#,{type="rect"}] #The output window size and position to render.

[engine.resource]
location = "%LOCAL%/ds_waffles/"
resource_db = "db.sqlite"

[engine.bridgesync]
#whether to use the local path to the shared path to find bridgesync.
app_path = "c:/downstream/bridgesync/bridge_sync_console.exe"
launch_bridgesync = true

[engine.bridgesync.connection]
server = "http://api.waffles.localhost"
#server = "https://app.hpi1.dev.bridge.downstream.com"
#auth_server = "https://hpi1-api-userpool.auth.us-east-2.amazoncognito.com"
#client_id = ""
#client_secret= ""
directory="%LOCAL%/dsdemo/"
interval = 5
verbose = true

[engine.logging]
rules=[[
    "*.verbose=false", #turn off all verbose
    "settings.*=true",
    "reloadUrl.*=false",
    "bridgeSync.app=true",
]]



